app/blueprints/main/routes.py
from flask import Blueprint, render_template

from app.services import blog_services, info_services


bp = Blueprint('main', __name__)

@bp.route("/")
def index():
    latest_post = blog_services.get_latest_post()
    info_data = info_services.get_info_date()
    return render_template('main/index.html', latest_post=latest_post, info_data=info_data)

@bp.route('/blog')
def blog():
    blogs = blog_services.get_all_blogs()
    return render_template('main/blog.html', blogs=blogs)

@bp.route('/information')
def information():
    info_data = info_services.get_info_date()
    return render_template('main/information.html', info=info_data)

@bp.route('/<int:post_id>/readmore')
def readmore(post_id):
    post = blog_services.get_post(post_id)
    return render_template('main/readmore.html', post=post)

app/templates/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}○○保育園{% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-custom fixed-top">
            <div class="container">
                <a class="navbar-brand" href="{{url_for('main.index')}}">○○保育園</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <ul class="navbar-nav navbar-center mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{{url_for('main.index')}}">ホーム</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.information') }}">施設概要</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.blog') }}">保育のようす</a>
                        </li>
                    </ul>
                    <div class="navbar-side ms-auto d-flex align-items-center">
                        {% if current_user.is_authenticated %}

                        <a href="{{ url_for('admin.admin') }}"
                            class="nav-link d-flex align-items-center gap-1 admin-link" title="管理画面へ">
                            <i class="bi bi-person-circle"></i>
                            管理ページ
                        </a>
                        {% endif %}
                    </div>

                </div>

            </div>
        </nav>
    </header>

    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
        {% endfor %}
        {% endwith %}
    </div>

    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='js/app.js')}}"></script>
</body>

</html>